version: "3.5"

services:
  pxc-master:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxc-master
    restart: always
    privileged: true
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - CLUSTER_NAME=pxc
    volumes:
      - $PWD/data:/var/lib/mysql

networks:
  default:
    external:
      name: mysql_net